### ISSUE TITLE
Curate and document the common concepts and terminology of Crossplane

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#636]
Curate glossary terms and concepts from all existing usage and converge on a shared set of well-defined concepts and language that we can use going forward.

Part of #625

### What seems to be the problem?
Crossplane has made a ton of progress since 0.2 and usage of concepts and language has evolved rapidly which can be confusing.

### What could Crossplane do to help?
Make it simple for new users to quickly understand Crossplane concepts and have a consistent experience in all their interactions with all docs, examples, crossplane.io, blog posts, etc.

We are currently thinking that we could update the existing concepts.md file to introduce concepts, and add a glossary.md file to define common terms.

### What does it look like when we're done?
A user can:
* Read some documentation and see a visual diagram to quickly understand all core concepts in Crossplane
* Easily look up common terms to quickly find consistent definitions of things

### Todo
- [ ] Update crossplane/concepts.md with new & consistent terms
- [ ] Add visual diragram to crossplane/concepts.md showing relationship between concepts
- [ ] Create crossplane/glossary.md with a comprehensive list of terms and definitions

**Comment by jbw976** [comment]
Fixed in #814
