### ISSUE TITLE
Azure: Define new networking types and controllers

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#647]
Add CRD's and controllers for Azure networking types required by Wordpress demo.

Part of #617

### What seems to be the problem?

In order to provision a functioning Wordpress application on Azure, the AKS cluster that the Wordpress container(s) runs in must be able to talk to the MySQL database. In order to do so, the MySQL database must have a [Virtual Network Rule](https://docs.microsoft.com/en-us/azure/mysql/howto-manage-vnet-using-portal?toc=%2fazure%2fvirtual-network%2ftoc.json) that allows access from the Subnet / Virtual Network that the AKS cluster nodes reside in. Currently, all described networking components (Subnet, Virtual Network, Virtual Network Rule) are created manually and have no representation within Crossplane.

Relevant Azure documentation [here](https://docs.microsoft.com/en-us/azure/mysql/concepts-data-access-and-security-vnet).

Note: For initial implementation, Virtual Network Rules are being chosen over Firewall Rules per Azure recommendation.

### What could Crossplane do to help?

The ability to provision network resources from within Crossplane allows for a more seamless user experience and allows for infrastructure resources to reference existing Kubernetes objects when specifying network components. Crossplane should create resource kinds and controllers that represent networking components in Azure.

### What does it look like when we're done?
A user can:

* Provision a Virtual Network resource that is managed by a corresponding Crossplane controller
* Provision a Subnet resourse that is managed by a corresponding Crossplane controller
* Provision a Virtual Network Rule resource that is managed by a corresponding Crossplane controller

### Todo
- [x] Create CRD and controller for Virtual Network resource kind.
- [x] Create CRD and controller for Subnet resource kind.
- [x] Create CRD and controller for Virtual Network Rule resource kind.

**Comment by hasheddan** [comment]
Closed by #721
