### ISSUE TITLE
Azure: High fidelity API and generic managed reconciler for all existing Azure resources (for v1alpha2)

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#648]
Migrate existing Azure infrastructure resource kinds to using the generic managed reconciler, and ensure that the API's are a high fidelity representation of the external resource.

Part of #617
Depends on #269 

### What seems to be the problem?

Throughout the development of Crossplane, reconcilers for managed resource kinds have diverged in how they are structured and operate. There is a desire to converge on a single managed reconciler pattern, which was implemented with #603. No Azure resources currently utilize the generic managed reconciler. In addition, some Azure resources do not support every configurable connectivity-related field available to the external resource API.

### What could Crossplane do to help?

All Azure resources should be updated to use the generic managed reconciler in their managed resource controller. It should also be ensured that all existing Azure resource kinds support the required connectivity fields (i.e. are high fidelity).

### What does it look like when we're done?

* All existing Azure resource kinds use the generic managed reconciler.
* All existing Azure resource kinds support fields required to orchestrate resource connectivity.
* Azure resources have been moved to updated API version `v1alpha2`.

### Todo
- [ ] Update Azure Cache for Redis managed controller to use generic managed reconciler.
- [ ] Update Azure AKS Cluster managed controller to use generic managed reconciler.
- [ ] Update Azure SQL Server managed controller to use generic managed reconciler.
- [ ] Update Azure PostgreSQL managed controller to use generic managed reconciler.
- [ ] Update Azure MySQL managed controller to use generic managed reconciler.
- [ ] Update Azure Storage Account managed controller to use generic managed reconciler.
- [ ] Update Azure Blob Storage managed controller to use generic managed reconciler.
- [ ] Update Azure Resource Group managed controller to use generic managed reconciler.
- [ ] Ensure high fidelity for all Azure resource kinds.
