### ISSUE TITLE
Create and publish GCP stack

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#651]
Part of #612

### What seems to be the problem?
As part of #612, we will be splitting out the cloud providers into their own repos and creating a stack for each of them.

### What could Crossplane do to help?
Crossplane can bootstrap this effort by creating the repository and metadata information to build and publish the GCP stack to a public registry.

### What does it look like when we're done?
* There will be a new GCP repo under the Crossplane org
* The GCP repo will contain all stack related metadata and config information necessary to build a stack
* The stack will be published to a public registry
* WordPress will be validated end to end to ensure no functional regressions and that WordPress is accessible and secure

### Todo
- [ ] Create new GCP repo
- [ ] Author stack content metadata/config
- [ ] Build GCP stack
- [ ] Publish GCP stack
- [ ] Verify WordPress e2e on top of the GCP stack

**Comment by jbw976** [comment]
The GCP stack repo has been created in https://github.com/crossplaneio/stack-gcp.

The initial GCP stack has been published to docker hub as `crossplane/stack-gcp`: https://cloud.docker.com/u/crossplane/repository/docker/crossplane/stack-gcp
