### ISSUE TITLE
Create and publish AWS stack

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#652]
Part of #612

### What seems to be the problem?
As part of #612, we will be splitting out the cloud providers into their own repos and creating a stack for each of them.

### What could Crossplane do to help?
Crossplane can bootstrap this effort by creating the repository and metadata information to build and publish the AWS stack to a public registry.

### What does it look like when we're done?
* There will be a new AWS repo under the Crossplane org
* The AWS repo will contain all stack related metadata and config information necessary to build a stack
* The stack will be published to a public registry
* WordPress will be validated end to end to ensure no functional regressions and that WordPress is accessible and secure

### Todo
- [ ] Create new AWS repo
- [ ] Author stack content metadata/config
- [ ] Build AWS stack
- [ ] Publish AWS stack
- [ ] Verify WordPress e2e on top of the AWS stack using #572 or existing documented version, whatever is available when this is ready for testing

**Comment by jbw976** [comment]
The AWS stack repo has been created in https://github.com/crossplaneio/stack-aws.

The initial AWS stack has been published to docker hub as `crossplane/stack-aws`: https://cloud.docker.com/u/crossplane/repository/docker/crossplane/stack-aws

Remaining work for official build pipelines is being tracked in #739.
