### ISSUE TITLE
GCP: Support for Network Resource with High Fidelity

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#654]
Network resource in GCP to be used for connecting different managed resources.

Part of #615 

### What seems to be the problem?
We need to manage the network for managed resources in GCP to have different resources be able to connect to each other. See https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-connectivity-mvp.md for connectivity architecture.

### What could Crossplane do to help?
Have support for a new CRD specific to GCP's `Network` with high fidelity.

### What does it look like when we're done?
A managed resource that we can connect different resources to each other in GCP. It should have all of the configurable options that GCP provides.

### Todo
- [ ] Create new group for networking if it doesn't exist.
- [ ] Create GCP network CRD struct and its boilerplate.
- [ ] Implement `ExternalClient` and `ExternalConnecter` interface functions in its generic managed reconciler.
- [ ] Update design doc
