### ISSUE TITLE
GCP: Support for Subnetwork Resource with High Fidelity

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#657]
This issue description is pretty much identical to #654 but for Subnetwork resource.

Subnetwork resource in GCP to be used for connecting different managed resources.

Part of #615 

### What seems to be the problem?
We need to manage the subnetwork for managed resources in GCP to have different resources be able to connect to each other. See https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-connectivity-mvp.md for connectivity architecture.

### What could Crossplane do to help?
Have support for a new CRD specific to GCP's `Subnetwork` with high fidelity.

### What does it look like when we're done?
A managed resource that we can connect different resources to each other in GCP. It should have all of the configurable options that GCP provides.

### Todo
- [ ] Create new group for networking if it doesn't exist.
- [ ] Create GCP subnetwork CRD struct and its boilerplate.
- [ ] Implement `ExternalClient` and `ExternalConnecter` interface functions in its generic managed reconciler.

**Comment by muvaf** [comment]
Fixed in #699
