### ISSUE TITLE
Implement strongly typed resource classes for all existing managed resources

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#662]
Take the pattern implemented for GCP CloudMemorystore [#643] and implement across all managed kinds in the Crossplane repo.

Part of #613 
Depends on #634 / #643 

### What seems to be the problem?

It is desired for every existing managed resource kind to have a corresponding strongly typed resource class. This allows for verification / validation of resource parameters, usage of UI annotations on CRD's, and a simpler claim reconciliation process.

### What could Crossplane do to help?

Crossplane should implement strongly typed resource classes for every managed resource kind, then follow the steps outlined in #643 to update the related tests and controllers.

### What does it look like when we're done?
A user can:

* Create a strongly typed resource class for any managed kind.
* Default any abstract (claim) kind to a strongly typed resource class using a `Policy`.
* Annotate CRD's with UI schemas.
* Validate appropriate parameters for a strongly typed resource class upon its creation, not upon its usage.

### Todo
- [ ] Add strongly typed resource class kinds for each managed kind.
- [ ] Refactor claim reconcilers to use strongly typed resource classes.
- [ ] Refactor tests to use strongly typed resource classes.

**Note**: a more detailed list of steps can "Todo's" can be found in #643
