### ISSUE TITLE
Update Quickstart Guide for crossplane.io docs

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#777]
### What problem are you facing?
Would like a quick start for Crossplane to get started ideally in < 1 min

part of #625

### How could Crossplane help solve your problem?
Updated [Quickstart Guide](https://crossplane.io/docs/v0.2/quick-start.html)
 * S0: Quickstart: Static provisioning of managed DB, consume via claim, show real usage by app
 * Overview / Intro - [DRAFT](https://docs.google.com/document/d/1NtMEEzRqYCn9-H_pE75nGLb1DqOn7KqXLbEc01GjAUA/edit?usp=sharing)
 * Deploy static DB - similar to what you know today?
  * Done in < 1 min - ideally
  * Single scenarios, most basic thing, even more stripped down than any other documentation

See the [complete v0.3 docs plan](https://docs.google.com/document/d/11SQHf1v_1iisgVqbGwdRnEOmpoAMpbiEglb_H664To4/edit?usp=sharing) for more detail

### Todo
 - [ ] Finalize [DRAFT](https://docs.google.com/document/d/1NtMEEzRqYCn9-H_pE75nGLb1DqOn7KqXLbEc01GjAUA/edit?usp=sharing)
 - [ ] Updated [Quick Start](https://crossplane.io/docs/v0.2/quick-start.html) Intro page
   - [ ] AWS Quick Start
   - [ ] GCP Quick Start
   - [ ] Azure Quick Start
