### ISSUE TITLE
Add Services Guide to getting-started.md on crossplane.io docs

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#778]
### What problem are you facing?
Would like to get started with dynamic provisioning using Crossplane Services by installing a Stack for GCP, AWS, or Azure and provisioning a managed DB instance using kubectl and securely use it from my app.

part of #625

### How could Crossplane help solve your problem?
Add a [Getting Started](https://crossplane.io/docs/v0.2/getting-started.html) section for:
 *  S1: Services Guide: Dynamic provisioning DB on single k8s cluster

See the [complete v0.3 docs plan](https://docs.google.com/document/d/11SQHf1v_1iisgVqbGwdRnEOmpoAMpbiEglb_H664To4/edit?usp=sharing) for more detail

### Todo:
 - [x] Finalize [DRAFT](https://docs.google.com/document/d/1C_Z1Ic95NFHsXw_gWcM3IvdLVhcPNaOAVhbTb3BtcrA/edit?usp=sharing)
 - [x] Add an general overview page for S1: Service Guide: Dynamic provisioning DB on single k8s cluster
   - [ ] AWS Services Guide
   - [ ] GCP Services Guide
   - [ ] Azure Services Guide
