### ISSUE TITLE
Add Stacks Guide to getting-started.md on crossplane.io docs

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#779]
### What problem are you facing?
Would like to get started deploying a portable App Stack (e.g. Wordpress) into multiple clouds from kubectl using one of the Stacks for GCP, AWS, or Azure.

part of #625

### How could Crossplane help solve your problem?
Add a [Getting Started](https://crossplane.io/docs/v0.2/getting-started.html) section for:
 *  S3: Stacks Guide: Deploy portable Wordpress App Stack into GCP, AWS, or Azure

See the [complete v0.3 docs plan](https://docs.google.com/document/d/11SQHf1v_1iisgVqbGwdRnEOmpoAMpbiEglb_H664To4/edit?usp=sharing) for more detail

### Todo:
 - [ ] Finalize [DRAFT](https://docs.google.com/document/d/1jJncy5hZcarZU6w9YpqHeO_z1f1wx0pw9tDXS0tyUGE/edit)
 - [ ] Add an general overview page for S3: Stacks Guide: Deploy portable Wordpress App Stack into GCP, AWS, or Azure
   - [ ] AWS Stacks Guide 
   - [ ] GCP Stacks Guide
   - [ ] Azure Stacks Guide #650

**Comment by suskin** [comment]
There has been a lot of work happening here, and we should be good for now. It could benefit from a bit more testing; the AWS stack guide has had the least coverage. But worst case, if we find anything critical, we can do a patch release. I am going to close this
