### ISSUE TITLE
Update overall crossplane.io docs for v0.3

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#781]
### What problem are you facing?
Would like crossplane.io docs to reflect all the awesome stuff going on in v0.3.

### How could Crossplane help solve your problem?
Our current thinking is that the documentation should be updated to reflect the changes. An example of changes which could be made would be:
* A glossary of terms is published and used consistently everywhere
* Crossplane docs have been curated and updated to reflect the 0.3 release

### Todo
Update [crossplane.io documentation](https://crossplane.io/docs/master/).

This issue covers the overall crossplane.io docs cleanup effort, with sub-issues called out below for larger work items.

* [x] Update [Welcome page](https://crossplane.io/docs/v0.2/):
   * Table of contents with explanations, updated arch diagram, etc.
   * Pull from updated arch doc

* [x] Update [Quick Start Guide](https://crossplane.io/docs/v0.2/quick-start.html) #777
* [x] Update [Getting Started](https://crossplane.io/docs/v0.2/getting-started.html):
  * [x] Remove: current deploy.md content
  * [x] Add: Services Guide to getting-started.md: S1: Service Guide: Dynamic provisioning DB on single k8s cluster #778
  * [x] Add: Stacks Guide S3: Deploy portable Wordpress App Stack #779
  * [x] Add: Create a "hello world" stack in under 5 minutes
    * link to:[crossplane-cli](https://github.com/crossplaneio/crossplane-cli)
      * init, build, publish, install, test, uninstall
  * [ ] Add: Cluster Guide S5: deploy a managed k8s cluster from kubectl - #780
  * [x] Remove from top-level getting started, but reuse/repurpose as appropriate:
    * [Install](https://crossplane.io/docs/v0.2/install-crossplane.html) - standalone control plane
    * [Add Providers](https://crossplane.io/docs/v0.2/cloud-providers.html): GCP, AWS, Azure
    * [Deploy Workloads](https://crossplane.io/docs/v0.2/deploy.html)
      * [GCP Wordpress](https://crossplane.io/docs/v0.2/workloads/gcp/wordpress-gcp.html) 
      * [AWS Wordpress](https://crossplane.io/docs/v0.2/workloads/aws/wordpress-aws.html) 
      * [Azure Wordpress](https://crossplane.io/docs/v0.2/workloads/azure/wordpress-azure.html) 
    *  [x] Update/remove: running-resource.md - if removing, update links from stack-gcp|aws|azure repos
      * reduce to summary paragraph and link to relevant getting started scenarios above?
    * [x] troubleshooting.md - no updates 

  * [x] Update [Concepts](https://crossplane.io/docs/v0.2/concepts.html) #636
  * [ ] Update [Related Projects](https://crossplane.io/docs/v0.2/related-projects.html)
  * [x] [FAQ](https://crossplane.io/docs/v0.2/faqs.html) - no changes for now
  * [x] CRD Reference (new)
    * Intro paragraph and link to generated docs in all repos: 
      * [Generate Crossplane (Custom Resource) API documentation](https://github.com/crossplaneio/crossplane/issues/763) #763
      * browse generated docs from crossplane.io or link? top-level nav?
      * Links to per stack docs kept in the repo for each stack: 
          * generated, examples, likely even the guides as well.
      * Longer term: show stacks docs in the registry 

  * [x] [Infra Stack] Developer Guide (new)
      * Intro paragraph and link to: 
          * Infra Stack Developer Guide [#610](https://github.com/crossplaneio/crossplane/issues/610)
      * Scenario: Starting stack-gcp from scratch, how would you do that?
      * Stacks, CRD, controllers, etc.; @negz, @suskin, @jared
      * Extending a stack; building a new stack;
      * Using crossplane-cli init, build, push 

  * [x] [Contributing](https://crossplane.io/docs/v0.2/contributing.html) - no major changes
      * Contributing.md project structure, add new resources - can update later
          * P0: Delete the file tree structure that’s out of date - Nic has PR 

      * [Local Build and Test links](http://cluster/local/README.md) - update to use kind in addition to minikube? 

  *  [x] [Learn More](https://crossplane.io/docs/master/learn-more.html) - no changes
