### ISSUE TITLE
Curate, update, and test all Crossplane examples for v0.3

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#782]
### What problem are you facing?
* [crossplane.io examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples) for GCP, AWS, Azure stacks have fallen behind the large number of changes in the v0.3 release. 

The examples in [/cluster/examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples) are a little hard to find without searching around, so would be nice to have a top-level examples directory.

Are secrets scripts in the [/cluster/examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples) still needed?
*   aws-credentials.sh
*   gcp-credentials.sh

The table in [/cluster/examples/readme.md](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/README.md) 
has names that are not clear and aren't organized by apps vs. resources. 

The resources are not in a flat top level list, so you have to navigate the categories to see all the supported resource types.

### How could Crossplane help solve your problem?
Organize the examples and update them to work with the new AWS, GCP, and Azure stacks.

Note: If infra stacks start releasing on independent schedules, these examples will need to live with the stacks themselves so they can be updated on their own cadence, and be tagged with the release of the stack.

### Todo
 - [ ] Update the [Crossplane examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples) to work with the latest cloud provider stacks

 - [ ] Move [/cluster/examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples) to a top-level examples directory.

- [ ] Update or remove secrets scripts if no longer needed in [/cluster/examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples):
* aws-credentials.sh - gitlab only?
* gcp-credentials.sh - gitlab only?

- [ ] If secrets scripts are still needed in [/cluster/examples](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples) then add:
* azure-credentials.sh?

- [ ] Update the table in [/cluster/examples/readme.md](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/README.md) 
to be organized by apps vs. resources. 
  * apps (new proposed folder)
    * [ ] wordpress -> use for #778, move to attic, or delete?
    * [ ] workloads/kubernetes/wordpress -> move to attic?
    * [ ] stacks -> move to each stack so they're self contained per #658?
    * [ ] gitlab -> need to update this for AWS and GCP along with the guides referenced from the [crossplane + gitlab blog post](https://blog.crossplane.io/crossplane-composes-fully-managed-services-in-kubernetes-to-deploy-gitlab-into-multiple-clouds/)
  * resources (new proposed folder)
    * [ ] cache/rediscluster
    * [ ] storage/bucket
    * [ ] database
    * [ ] compute/kubernetescluster
