### ISSUE TITLE
Update crossplane repo docs including readme

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#783]
### What problem are you facing?
The main crossplane repo readme and repo-specific docs could use a refresh.

### How could Crossplane help solve your problem?
Refresh the [crossplaneio/crossplane](https://github.com/crossplaneio/crossplane) repo docs

### Todo 
* [ ] README.md - overall intro content
  *   [ ] General readme cleanup, tighter prose, more direct, approachable, etc.
  *   [ ] API Status table for portable types in this repo
*   [x] Roadmap.md update - #637

**Comment by negz** [comment]
I thiiiink this got done (the API status table was removed rather than updated). Dragging to closed - let me know if that is not accurate.
