### ISSUE TITLE
Claim-based dynamic provisioning of Rook-managed databases

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#862]
Rook stack, so I can provision in-cluster storage solutions on any k8s cluster.

Part of the [0.4 release](tbd)

### What seems to be the problem?
Would like to provision in-cluster Rook-managed databases from Crossplane, like CockroachDB and Yugabyte.

### What could Crossplane do to help?
Support claim-based dynamic provisioning of Rook-managed databases like CockroachDB, Yugabyte which provide PostgreSQL wire-level compatibility.

This doesn't need to setup Rook and could assume Rook runs in the same cluster as pods.

### What does it look like when we're done?
A Crossplane user can deploy a CockroachDB cluster or Yugabyte cluster in any Kubernetes cluster where the Rook operators are installed.

Support both embedded and standalone Crossplane instances.

### How could this be demonstrated?
Preconditions:
 - created cluster with Rook installed 
 - including operators for CockroachDB, Yugabyte

Steps:
1. Install Crossplane
1. Install `stack-rook`
1. Create a Kubernetes `Provider` that references a secret containing connection info for a Crossplane-provisioned K8s cluster, a pre-existing K8s cluster, or the control cluster itself (Rook operators must be installed in the target cluster).
1. Create a CockroachDB `ClusterClass` in Crossplane control cluster.
1. Create a `PostgreSQLInstancClass` that references the `ClusterClass`.
1. Create a `PostreSQLInstance` claim that references the `PostgreSQLInstancClass`.
1. CockroachDB cluster is created in target K8s cluster and connection secret is propagated to claim namespace in control cluster.

### Related Issues
 * [x] [#841] Design 1-pager
 * [x] [#842] Investigate Initial Rook integration
 * [x] [#872] Implement Kubernetes Provider
 * [x] [#901] Stack creation
 * [x] [#885] Create Rook Yugabyte Cluster CRDs and controllers
 * [x] [#884] Create Rook CockroachDB Cluster CRDs and controllers
 * [x] [#903] Crossplane.io docs
