### ISSUE TITLE
Stable v1beta1 APIs for managed databases and caches

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#863]
Beta meta model w/ DB & Redis, so users can deploy to dev/test/prod, align on shape of APIs & best practices, high-def CRDs & controllers, to provide a basis for for code generation in a future milestone.

Part of the [0.4 release](tbd)

### What seems to be the problem?
APIs are currently v1alpha and would like more stable v1beta APIs, so I can take a dependency on Crossplane in my dev/test/prod environments for key managed resources like databases and caches.

### What could Crossplane do to help?
Align on shape of APIs & best practices across stacks, define a consistent Crossplane meta model as extensions to Kubernetes, model high-def CRDs and controllers for PostgreSQL, MySQL, and Redis.

### What does it look like when we're done?
GCP, AWS and Azure database and Redis resources should be upgraded to v1beta1, which requires them to be refactored to use generic managed reconciler and adopt the patterns in [managed resources api patterns one-pager](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-managed-resource-api-design.md).

### How could this be demonstrated?
Possibly a demo showing how Crossplane covers most (if not all) possible configurations that you can have for these resources and consistency between their CR forms.

### Related Issues
 - [x] [#831] Align on shape of APIs & best practices
   * Beta meta model w/ DB & Redis, so users can deploy to dev/test/prod
   * [x] https://github.com/crossplaneio/crossplane-runtime/pull/43 Naming scheme for all resources.
   * [x] [#624] Managed resource name as external name for all resources.
 * [x] https://github.com/crossplaneio/stack-gcp/issues/43 GCP CloudSQL and CloudMemoryInstance resources v1beta1
 * [x] https://github.com/crossplaneio/stack-aws/issues/30 AWS RDS and ReplicationGroup resources v1beta1
 * [ ] https://github.com/crossplaneio/stack-azure/issues/28 Azure SQL and Redis resources v1beta1

### Nice to have
[#933] v1beta1 quality conformance doc
