### ISSUE TITLE
Simple Resource Class Selection

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#952]
### What problem are you facing?

This is a very lazily written epic tracking the Simple Resource Class Selection work. See https://github.com/crossplaneio/crossplane/pull/926 for details on the changes.

### How could Crossplane help solve your problem?

- [x] https://github.com/crossplaneio/crossplane-runtime/pull/48 - Update runtime
- [x] https://github.com/crossplaneio/crossplane-tools/pull/7 - Update tools
- [x] https://github.com/crossplaneio/crossplane/pull/927 - Update core
- [x] https://github.com/crossplaneio/stack-azure/pull/35 - Update Azure
- [x] https://github.com/crossplaneio/stack-gcp/pull/56 - Update GCP
- [x] https://github.com/crossplaneio/stack-aws/pull/44 - Update AWS
- [x] https://github.com/crossplaneio/stack-rook/pull/5 - Update Rook
- [x] https://github.com/crossplaneio/crossplane/pull/963 - Update examples
- [x] https://github.com/crossplaneio/crossplane/pull/973 - Update Services Developer Guide
- [x] https://github.com/crossplaneio/crossplane/pull/975 - Update Services Guide
- [x] https://github.com/crossplaneio/crossplane/pull/965 - Update Stacks Guide

Edit: I don't want to block this epic on generating new API docs. Raised https://github.com/crossplaneio/crossplane/issues/970 to track that.

**Comment by negz** [comment]
Bonus points: confirm after merging everything whether https://github.com/crossplaneio/crossplane/issues/319 is fixed.
